/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  11155111: {
    ArbiterContract: {
      address: "0xd32821572710444a37f26FBAC1b216d9C0857C3C",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_realitio",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_arbitrationFee",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "question_id",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "requester",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "fee",
              type: "uint256",
            },
          ],
          name: "ArbitrationRequested",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "question_id",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "answer",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "address",
              name: "answerer",
              type: "address",
            },
          ],
          name: "ArbitrationSettled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "newFee",
              type: "uint256",
            },
          ],
          name: "FeeUpdated",
          type: "event",
        },
        {
          inputs: [],
          name: "arbitrationFee",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "arbitrationRequests",
          outputs: [
            {
              internalType: "address",
              name: "requester",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "feePaid",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isPending",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "isSettled",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "question_id",
              type: "bytes32",
            },
          ],
          name: "getArbitrationRequest",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "requester",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "feePaid",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isPending",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "isSettled",
                  type: "bool",
                },
              ],
              internalType: "struct ArbiterContract.ArbitrationRequest",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "question_id",
              type: "bytes32",
            },
          ],
          name: "getDisputeFee",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "question_id",
              type: "bytes32",
            },
          ],
          name: "isArbitrationPending",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "realitio",
          outputs: [
            {
              internalType: "contract IRealityETH",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "question_id",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "lastSeenBond",
              type: "uint256",
            },
          ],
          name: "requestArbitration",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "question_id",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "answer",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "answerer",
              type: "address",
            },
          ],
          name: "submitArbitrationAnswer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "question_id",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "answer",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "payee_if_wrong",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "last_history_hash",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "last_answer_or_commitment_id",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "last_answerer",
              type: "address",
            },
          ],
          name: "submitArbitrationAnswerWithWinner",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "newFee",
              type: "uint256",
            },
          ],
          name: "updateArbitrationFee",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "withdrawFees",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      receipt: {
        to: null,
        from: "0xAd98E5E1745F4040361015a5E2325ca94e4312F7",
        contractAddress: "0xd32821572710444a37f26FBAC1b216d9C0857C3C",
        transactionIndex: 67,
        gasUsed: "783948",
        logsBloom:
          "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        blockHash: "0x93eddd9835c1c7ce53bf12756b599e341b03354c582341678f2f365aaa91e009",
        transactionHash: "0xf138a3973c82b4baba590ff5ad0f787a8704529181a138ed136e449c413f4e80",
        logs: [],
        blockNumber: 9277769,
        cumulativeGasUsed: "9716973",
        status: 1,
        byzantium: true,
      },
    },
    GigsContract: {
      address: "0x82fC0b81C489B9D1D1083b46beA00544d996496F",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "gigId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "applicationId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "finalPayment",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "finalDurationInHours",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "ApplicationAccepted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "gigId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "applicationId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "rejectionComment",
              type: "string",
            },
          ],
          name: "ApplicationRejected",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "gigId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "applicationId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "proposedPayment",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "proposedDurationInHours",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "proposalComment",
              type: "string",
            },
          ],
          name: "ApplicationSubmitted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "gigId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "applicationId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "rejectionComment",
              type: "string",
            },
          ],
          name: "ApplicationWithdrawn",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "gigId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "ClientMarkedAsReceived",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "gigId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "response",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "fileUploadedAt",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "CommentAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "gigId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "resource",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "submissionComment",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isLink",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "uploadedAt",
              type: "uint256",
            },
          ],
          name: "FileUploaded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "gigId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "FreelancerMarkedAsDelivered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "gigId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "enum GigsContract.GigState",
              name: "state",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "clientCancelled",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "freelancerCancelled",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "GigCancelled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "gigId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "payment",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "GigCompleted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "gigId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "basePayment",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "title",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "category",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "maxDurationInHours",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "gigBannerImageHash",
              type: "string",
            },
          ],
          name: "GigCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "gigId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "rating",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "GigRated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "gigId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "freelancerDelivered",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "clientReceived",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "clientRejected",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "GigRejected",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_gigId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_applicationId",
              type: "uint256",
            },
          ],
          name: "acceptApplication",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_gigId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_comment",
              type: "string",
            },
          ],
          name: "addCommentToGig",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_gigId",
              type: "uint256",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "proposedPayment",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "proposedDurationInHours",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "proposal",
                  type: "string",
                },
              ],
              internalType: "struct GigsContract.ApplicationParams",
              name: "params",
              type: "tuple",
            },
          ],
          name: "applyToGig",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_gigId",
              type: "uint256",
            },
          ],
          name: "cancelGig",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_gigId",
              type: "uint256",
            },
          ],
          name: "confirmCompletion",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "string",
                  name: "title",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "description",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "category",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "maxDurationInHours",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "gigBannerImageHash",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "basePayment",
                  type: "uint256",
                },
              ],
              internalType: "struct GigsContract.GigParams",
              name: "params",
              type: "tuple",
            },
          ],
          name: "createGig",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_gigId",
              type: "uint256",
            },
          ],
          name: "emergencyCancel",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "getTotalGigsPosted",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "postedGigs",
          outputs: [
            {
              internalType: "uint256",
              name: "gigId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              internalType: "address",
              name: "acceptedFreelancer",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "basePayment",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "finalPayment",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "title",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "category",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "maxDurationInHours",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "finalDurationInHours",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
            {
              internalType: "enum GigsContract.GigState",
              name: "state",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "createdAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "acceptedAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "canceledAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "rejectedAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "finishedAt",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "clientReceived",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "freelancerDelivered",
              type: "bool",
            },
            {
              internalType: "uint8",
              name: "rating",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "acceptedApplicationId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "gigBannerImageHash",
              type: "string",
            },
            {
              internalType: "bool",
              name: "clientRejected",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "clientCancelled",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "freelancerCancelled",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "postedGigsCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_gigId",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "_rating",
              type: "uint8",
            },
          ],
          name: "rateGig",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_gigId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_applicationId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_rejectionComment",
              type: "string",
            },
          ],
          name: "rejectApplication",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_gigId",
              type: "uint256",
            },
          ],
          name: "rejectGig",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_gigId",
              type: "uint256",
            },
            {
              components: [
                {
                  internalType: "string",
                  name: "resource",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "submissionComment",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "isLink",
                  type: "bool",
                },
              ],
              internalType: "struct FileParams",
              name: "_fileParams",
              type: "tuple",
            },
          ],
          name: "uploadFile",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_gigId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_applicationId",
              type: "uint256",
            },
          ],
          name: "withdrawApplication",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      receipt: {
        to: null,
        from: "0xAd98E5E1745F4040361015a5E2325ca94e4312F7",
        contractAddress: "0x82fC0b81C489B9D1D1083b46beA00544d996496F",
        transactionIndex: 69,
        gasUsed: "2832343",
        logsBloom:
          "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        blockHash: "0xdbbe87086f60b81f48422813c21cba87bcc00d9b793c14db45e69bed6496f3d6",
        transactionHash: "0xa28cd915eaf45f2c235b950681874c8f203ecdb4220a5703c4216cf2a7016757",
        logs: [],
        blockNumber: 9198534,
        cumulativeGasUsed: "12748266",
        status: 1,
        byzantium: true,
      },
    },
    JobsContract: {
      address: "0xc98d2Dd5a37E0297796dE820f319b8bCf202Dc23",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "_reality",
              type: "address",
            },
            {
              internalType: "address",
              name: "_arbitrator",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "postingId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "ClientMarkedAsReceived",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "postingId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "response",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "fileUploadedAt",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "CommentAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "postingId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "questionId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "requester",
              type: "address",
            },
          ],
          name: "DisputeStarted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "postingId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "resource",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "submissionComment",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isLink",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "FileUploaded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "postingId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "FreelancerMarkedAsDelivered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "postingId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "JobAccepted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "postingId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "enum JobsContract.JobState",
              name: "state",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "clientCancelled",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "freelancerCancelled",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "JobCancelled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "postingId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "payment",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "title",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "category",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "bannerImageHash",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "jobDuration",
              type: "uint256",
            },
          ],
          name: "JobCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "postingId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "payment",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "JobFinished",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "postingId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "basePayment",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "title",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "category",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "bannerImageHash",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "minimumNoticeTime",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "averageWorkDuration",
              type: "uint256",
            },
          ],
          name: "JobPostingCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "postingId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "rating",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "JobRated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "postingId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "freelancerDelivered",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "clientReceived",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "clientRejected",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "JobRejected",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_postingId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_jobId",
              type: "uint256",
            },
          ],
          name: "acceptJob",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_postingId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_jobId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_comment",
              type: "string",
            },
          ],
          name: "addCommentToJob",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "arbitratorAddress",
          outputs: [
            {
              internalType: "contract IArbiterContract",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_postingId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_jobId",
              type: "uint256",
            },
          ],
          name: "cancelJob",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_postingId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_jobId",
              type: "uint256",
            },
          ],
          name: "confirmCompletion",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_postingId",
              type: "uint256",
            },
            {
              components: [
                {
                  internalType: "string",
                  name: "title",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "description",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "payment",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "durationInHours",
                  type: "uint256",
                },
              ],
              internalType: "struct JobsContract.JobParams",
              name: "params",
              type: "tuple",
            },
          ],
          name: "createJob",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "string",
                  name: "title",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "description",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "category",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "bannerImageHash",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "basePayment",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "minimumNoticeTime",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "averageWorkDuration",
                  type: "uint256",
                },
              ],
              internalType: "struct JobsContract.JobPostingParams",
              name: "params",
              type: "tuple",
            },
          ],
          name: "createJobPosting",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_postingId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_jobId",
              type: "uint256",
            },
          ],
          name: "emergencyCancel",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_postingId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_jobId",
              type: "uint256",
            },
          ],
          name: "getDisputeResult",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_postingId",
              type: "uint256",
            },
          ],
          name: "getJobCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getTotalJobsPosted",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "postingId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "comment",
              type: "string",
            },
            {
              internalType: "string",
              name: "ipfsHash",
              type: "string",
            },
          ],
          name: "isFileUploaded",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "postedJobs",
          outputs: [
            {
              internalType: "uint256",
              name: "postingId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "basePayment",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "title",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "category",
              type: "string",
            },
            {
              internalType: "string",
              name: "bannerImageHash",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "minimumNoticeTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "averageWorkDuration",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "createdAt",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "postedJobsCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_postingId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_jobId",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "_rating",
              type: "uint8",
            },
          ],
          name: "rateJob",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "reality",
          outputs: [
            {
              internalType: "contract IRealityETH",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_postingId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_jobId",
              type: "uint256",
            },
          ],
          name: "rejectJob",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_postingId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_jobId",
              type: "uint256",
            },
          ],
          name: "resolveDispute",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_postingId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_jobId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_comment",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "_bountyAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_bondAmount",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "_escalateToArbitrator",
              type: "bool",
            },
          ],
          name: "startDispute",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_postingId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_jobId",
              type: "uint256",
            },
            {
              components: [
                {
                  internalType: "string",
                  name: "resource",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "submissionComment",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "isLink",
                  type: "bool",
                },
              ],
              internalType: "struct FileParams",
              name: "_fileParams",
              type: "tuple",
            },
          ],
          name: "uploadFile",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      receipt: {
        to: null,
        from: "0xAd98E5E1745F4040361015a5E2325ca94e4312F7",
        contractAddress: "0xc98d2Dd5a37E0297796dE820f319b8bCf202Dc23",
        transactionIndex: 77,
        gasUsed: "3880151",
        logsBloom:
          "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        blockHash: "0xb6d9a67cb0291e4946b66e1de2d68431db1d2b0be98d20c6492d90e480051b2a",
        transactionHash: "0x8afc6b4fc799d2df0d5b20f4461b3f81a491217fbf491cd28518b5dc70a6d645",
        logs: [],
        blockNumber: 9281200,
        cumulativeGasUsed: "36600539",
        status: 1,
        byzantium: true,
      },
    },
    NotificationsContract: {
      address: "0x667Cd53f79c9fAC027Ecc07BECCcA0208C997a01",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string[]",
              name: "ids",
              type: "string[]",
            },
            {
              indexed: false,
              internalType: "enum NotificationStatus",
              name: "status",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "ChangeNotificationsStatus",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string[]",
              name: "ids",
              type: "string[]",
            },
            {
              internalType: "enum NotificationStatus",
              name: "status",
              type: "uint8",
            },
          ],
          name: "changeNotificationsStatus",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      receipt: {
        to: null,
        from: "0xAd98E5E1745F4040361015a5E2325ca94e4312F7",
        contractAddress: "0x667Cd53f79c9fAC027Ecc07BECCcA0208C997a01",
        transactionIndex: 71,
        gasUsed: "144627",
        logsBloom:
          "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        blockHash: "0x05920a8454d5bf84e2860962e7bc83021a9bc1974f76caf27fb6bbc1bf59de64",
        transactionHash: "0x0c80df92d4ddefc8a39e561fc77e7637d4901e0ff63b0c8cf279929e112d4a67",
        logs: [],
        blockNumber: 9198536,
        cumulativeGasUsed: "5956415",
        status: 1,
        byzantium: true,
      },
    },
    ProfileConfigContract: {
      address: "0xd50638EDdE512B16f7e42C71caA109402049714A",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "string",
                  name: "username",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "profilePicture",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "bannerPicture",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "biography",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "email",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "xUrl",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "instagramUrl",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "linkedinUrl",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "artstationUrl",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "sketchfabUrl",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "customUrl",
                  type: "string",
                },
              ],
              indexed: false,
              internalType: "struct ProfileConfigContract.Profile",
              name: "profile",
              type: "tuple",
            },
          ],
          name: "ProfileUpdated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "getProfile",
          outputs: [
            {
              components: [
                {
                  internalType: "string",
                  name: "username",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "profilePicture",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "bannerPicture",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "biography",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "email",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "xUrl",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "instagramUrl",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "linkedinUrl",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "artstationUrl",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "sketchfabUrl",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "customUrl",
                  type: "string",
                },
              ],
              internalType: "struct ProfileConfigContract.Profile",
              name: "profileData",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "string",
                  name: "username",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "profilePicture",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "bannerPicture",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "biography",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "email",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "xUrl",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "instagramUrl",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "linkedinUrl",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "artstationUrl",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "sketchfabUrl",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "customUrl",
                  type: "string",
                },
              ],
              internalType: "struct ProfileConfigContract.Profile",
              name: "profileData",
              type: "tuple",
            },
          ],
          name: "setProfile",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      receipt: {
        to: null,
        from: "0xAd98E5E1745F4040361015a5E2325ca94e4312F7",
        contractAddress: "0xd50638EDdE512B16f7e42C71caA109402049714A",
        transactionIndex: 79,
        gasUsed: "1931107",
        logsBloom:
          "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        blockHash: "0x632a49e2ee413f55a1ca852f846735028792359addbd346e83ee7e8576d11ec8",
        transactionHash: "0x7621d1f90c00f45c0eb63f1a5ab89b29986ccf383089b8e5d71f3ebde6c40307",
        logs: [],
        blockNumber: 9198535,
        cumulativeGasUsed: "45916667",
        status: 1,
        byzantium: true,
      },
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
